# Use an official nginx image
FROM nginx:alpine

# Copy the static files to the nginx directory
COPY ./usr/share/nginx/html /usr/share/nginx/html
# Expose port 80
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
